# Generated by Django 3.2.5 on 2021-07-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('students_in_group', models.IntegerField(verbose_name='Students in group')),
            ],
        ),
    ]
